### NumPy Library

* NumPy stands for Numerical Python.
* NumPy is a standard library used for matrix application, multidimensional problematic applications etc.

* NumPy is a python library used for working with arrays.
* It is also has functions for working in domain of linear algebra , fourier transform and matrices.
* Numpy aims to provide an array object which is much faster than traditional python.
* Array : An array is a datastructure that stores a collection of elements, typically of the same type , the elements in array are indexed, which means elements have specific positions or "index" that allows you to access it directly.

***Import Library***

To utilize NumPy we need to import library and mention it with an alias.

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)  # [1 2 3 4 5]
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


* Array are considered of different types such as :
1. 0-D array : 0-D array or scalars are the elements in an array. each value in array is a 0-D array.

2. 1-D array : 1-D array are the elements which are having only one diemnsion and these are common arrays.

3. 2-D array : 2-D array are the elements which represents matrix having both dimensions.

4. 3-D array : 3-D array are the array which has @-D matrix as its elements and follow #rd order tensor.

In [8]:
#1
arr = np.array(42)
print(arr)

print("----------------------------")

arr1 = np.array([1,2,3,4,5,6])
print(arr1)

print("----------------------------")

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

print("----------------------------")

arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

42
----------------------------
[1 2 3 4 5 6]
----------------------------
[[1 2 3]
 [4 5 6]]
----------------------------
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


***No. of Dimensions in Array***

* In NumPy we can know the dimensions of the array by providing a code "ndim" function.

In [9]:
a = np.array(4)
b = np.array([1,2,3])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


***Access Array Elements***

* Array indexing means accessing the elements in array
* We can access the elements in the array through providing an index number of the element.

In [17]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[0])
print(arr[0:5])
print(arr[2:4])
print(arr[-1])
print(arr[-2:-5])

1
[1 2 3 4 5]
[3 4]
9
[]


In [4]:
print(arr[1:3]) 
print(arr[:3])  
print(arr[2:])  

[2 3]
[1 2 3]
[3 4 5]


* To acces elements from 2-D array we can use comma to seperate integers representing the dimensions and index the element.
* As it is in the table form with rows and columns we need to represent row index and then column index.

In [24]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr[0,2])
print(arr[1,1])

3
5


In [23]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,4])
print(arr[1,3])

5
9


* To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [28]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])
print(arr[1,1,2])
print(arr[0,0,2])
print(arr[1,0,2])

6
12
3
9


* We can use the negative indexing to access an array from the end.

In [34]:
arr = np.array([2,4,6,8,10,12,14])
print(arr[-1])
print(arr[-3])

14
10


In [32]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,-1])
print(arr[0,-2])
print(arr[1,-2])

10
4
9


***Slicing an array***

* Slicing in python means taking elements from one given index to another given index.
* We pass slice instead of index like this: [start:end].
* We can also define the step, like this: [start:end:step].
* If we don't pass start its considered 0
* If we don't pass end its considered length of array in that dimension
* If we don't pass step its considered 1

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:3])
print(arr[2:4])
print(arr[0:6])
print(arr[:3])
print(arr[2:])
print(arr[:-1])
print(arr[-1: ])

[2 3]
[3 4]
[1 2 3 4 5 6]
[1 2 3]
[3 4 5 6 7]
[1 2 3 4 5 6]
[7]


In [51]:
print(arr[1:6:2])
print(arr[0:6:2])
print(arr[::2])
print(arr[::3])

[2 4 6]
[1 3 5]
[1 3 5 7]
[1 4 7]


In [3]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

***Converting Datatype of an Array***
* The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

* The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [52]:
arr = np.array([1.1, 2.2, 3.3])
newarr = arr.astype("i")
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [53]:
arr = np.array([1,2,3,4,5,6])
newar = arr.astype("f")
print(newar)
print(newar.dtype)

[1. 2. 3. 4. 5. 6.]
float32


In [54]:
import numpy as np
arr = np.array([-1, 0, 1])
newarr = arr.astype(bool)
print(newarr)

[ True False  True]


***Element wise calculation in NumPy***
* In NumPy we can perform element calculations such as addition and substraction and other calculations.

In [56]:
arr1 = np.array([2,4,6])
arr2= np.array([1,3,5])
print(arr1 + arr2)  
print(arr1 * arr2)  

[ 3  7 11]
[ 2 12 30]


* We can also perform the operations in other way such as below code.

In [58]:
print(np.add(arr1, arr2))  
print(np.multiply(arr1, arr2)) 
print(np.divide(arr1, arr2)) 

[ 3  7 11]
[ 2 12 30]
[2.         1.33333333 1.2       ]


***Dot Product Calculation***

In [59]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(np.dot(arr1, arr2))  

[[19 22]
 [43 50]]


In [62]:
arr3 = np.array([[1,2],[4,5]])
arr4 = np.array([[1,2],[4,5]])
print(np.dot(arr3, arr4))

[[ 9 12]
 [24 33]]


***Statistical Calculation***
* Through NumPy we can also perform statistical caluclations wsuch as mean , meadian and standard deviation etc.

In [9]:
arr = np.array([1, 2, 3, 4, 5])
print(np.mean(arr))  
print(np.median(arr))  
print(np.std(arr))  

3.0
3.0
1.4142135623730951


In [66]:
arr_large = np.array([1000, 5000, 10000, 20000, 50000])
print(np.mean(arr_large))
print(np.median(arr_large))
print(np.std(arr_large))
print(np.var(arr_large))

17200.0
10000.0
17588.632692736523
309360000.0


In [68]:
arr_repeated = np.array([3] * 5)
print(np.mean(arr_repeated))
print(np.std(arr_repeated))

3.0
0.0


In [76]:
arr_decimal = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(np.min(arr_decimal))
print(np.max(arr_decimal))
print(np.quantile(arr_decimal, 0.25))  # 25% quantile 

0.1
0.5
0.2


In [75]:
arr_decimal = np.array([0.1, 0.2, 0.3, 0.4, 0.5])
print(np.sum(arr_decimal))
print(np.percentile(arr_decimal, 25))  # 25th percentile
print(np.percentile(arr_decimal, 50))  # 50th percentile (median)
print(np.percentile(arr_decimal, 75))  # 75th percentile


1.5
0.2
0.3
0.4


***Reshape of Array***
* we can reshape the elements position of the array without changing the elements.

In [78]:
arr4 = np.array([1, 2, 3, 4, 5, 6])
print(np.reshape(arr4, (2, 3))) 

[[1 2 3]
 [4 5 6]]


In [82]:
arr_odd = np.array([1, 3, 5, 7, 9])
print(np.reshape(arr_odd, (5, 1)))  # (5, 1)
print(np.reshape(arr_odd, (1, 5)))  # (1, 5)


[[1]
 [3]
 [5]
 [7]
 [9]]
[[1 3 5 7 9]]


In [87]:
arr_odd = np.array([1, 3, 5, 7, 9, 11])
print(np.reshape(arr_odd, (2, 3)))
print(np.reshape(arr_odd, (1,6)))
print(np.reshape(arr_odd, (6,1)))


[[ 1  3  5]
 [ 7  9 11]]
[[ 1  3  5  7  9 11]]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]]


***Tranpose function on Array***
* The np.transpose(arr) function transposes the array, swapping its rows and columns.
* The output will be:

In [89]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.transpose(arr))

[1 2 3 4 5 6]


In [88]:
arr = np.array([[1, 2], [3, 4]])
print(np.transpose(arr))

[[1 3]
 [2 4]]


In [91]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(np.transpose(arr))

[[1 3 5]
 [2 4 6]]


***Concatenate the arrays***

* We can concatenate the two individual arrays in numpy but there will be no order of regenarated arrayit just combine the arrays.

In [93]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [94]:
arr_even = np.array([2, 4, 6, 8, 10])
arr_odd = np.array([1, 3, 5, 7, 9])
print(np.concatenate((arr_even,arr_odd)))

[ 2  4  6  8 10  1  3  5  7  9]


In [95]:
arr_neg_float = np.array([-1.5, -2.3, -3.7, -4.9, -5.1])
arr_mixed = np.array([1, 2.5, 3, 4.1, 5])
print(np.concatenate((arr_neg_float,arr_mixed)))

[-1.5 -2.3 -3.7 -4.9 -5.1  1.   2.5  3.   4.1  5. ]


***Split of the Array***

* np.split ,splits the array arr into 2 equal parts. The function np.split() divides an array into multiple sub-arrays. The number 2 tells the function to split the array into 2 parts.


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 2)) 

[array([1, 2, 3]), array([4, 5, 6])]


In [98]:
arr_neg_float = np.array([-1.5, -2.3, -3.7, -4.9, -5.1 , -6.9])
print(np.split(arr_neg_float, 2))

[array([-1.5, -2.3, -3.7]), array([-4.9, -5.1, -6.9])]


***Implementing zero in Array***

np.zeroes provide the zeroes which are in float data type as an array.

In [99]:
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


***Explanation of the np.linspace() Function***

* np.linspace(start, stop, num) is a NumPy function that generates linearly spaced values between two given numbers, start and stop, with a specified number of points (num).

Here's the breakdown of the parameters:

* start: The starting value of the range (inclusive).
* stop: The end value of the range (inclusive).
* num: The number of evenly spaced values to generate between start and stop.


In [25]:
arr = np.linspace(0,1,5)
print(arr)

[0.   0.25 0.5  0.75 1.  ]


In [101]:
arr = np.linspace(0, 5, 10)
print(arr)


[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [102]:
arr = np.linspace(-1, 1, 4)
print(arr)


[-1.         -0.33333333  0.33333333  1.        ]


***Generating random elements in array***

* np.random.random() is a function in NumPy that generates an array of random numbers drawn from a uniform distribution between 0 and 1.

In [26]:
arr = np.random.random((3,3))
print(arr)

[[0.80895159 0.51869341 0.31394957]
 [0.41148044 0.93466031 0.38232737]
 [0.11430972 0.05417632 0.27893392]]


* Generate a random integer between 0 and 10 (exclusive)


In [27]:
random_int = np.random.randint(0, 10)
print(random_int)  


7


In [106]:
arr1 = np.random.randint(0,10)
arr2 = np.random.randint(0,10)
arr3 = np.random.randint(0,10)
print(arr1)
print(arr2)
print(arr3)

9
8
9


***Explanation of np.arange()***

* np.arange(start, stop, step) is a function in NumPy that generates an array of evenly spaced values over a specified range. 

In [107]:
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [109]:
arr = np.arange(1, 10, 1)
print(arr)


[1 2 3 4 5 6 7 8 9]


In [110]:
arr = np.arange(-10, 0, 2)
print(arr)


[-10  -8  -6  -4  -2]


In [111]:
arr = np.arange(0, 20, 5)
print(arr)


[ 0  5 10 15]


### Excercise

In [2]:
import numpy as np 

In [4]:
num = np.array([10,20,30,40,50])
print(num)

[10 20 30 40 50]


In [21]:
print(np.reshape(num,(5,1)))
num_1 = np.transpose(num)
print(num_1)

[[10]
 [20]
 [30]
 [40]
 [50]]
[10 20 30 40 50]


In [14]:
num_2 = np.array([2,4,6,8,10])
print(num_2)

[ 2  4  6  8 10]


In [16]:
print(num_1+num_2)
print(np.add(num_1,num_2))

[12 24 36 48 60]
[12 24 36 48 60]


In [17]:
print(num_1*num_2)
print(np.multiply(num_1,num_2))

[ 20  80 180 320 500]
[ 20  80 180 320 500]


In [24]:
res = np.reshape(num_2,(5,1))
print(res)
print(np.transpose(res))

[[ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]]
[[ 2  4  6  8 10]]


In [25]:
print(np.dot(num_1,res))

[1100]


In [27]:
print(np.mean(num_1))
print(np.mean(num_2))

30.0
6.0


In [28]:
print(np.median(num_1))
print(np.median(num_2))

30.0
6.0


In [29]:
print(np.std(num_1))
print(np.std(num_2))

14.142135623730951
2.8284271247461903


In [31]:
print(np.concatenate((num_1,num_2)))

[10 20 30 40 50  2  4  6  8 10]
